###
POST http://localhost:8080/api/users HTTP/1.1
Content-Type: application/json

{
  "celular":"43",
  "contrasenia":"hola",
  "email":"345",
  "nombre":"45",
  "pref_comida":"456",
  "ubi_actual":"456",
  "username":"345"

}

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/64ab61b49c1f22c002391c11 HTTP/1.1

###
GET http://localhost:9000/api/users/e/sajulia9@gmail.com HTTP/1.1


###

PUT http://localhost:9000/api/users/64ab61b49c1f22c002391c11 HTTP/1.1
Content-Type: application/json

{
  "nombre":"Silvia Ortiz",
  "celular":3152451707,
  "contrasenia":"silvia1234",
  "username":"silvia99",
  "pref_comida":"Rápidas",
  "ubi_actual":"Manizales,CO",
  "email":"sajulia9@gmail.com"

}


###

DELETE http://localhost:9000/api/users/64ab61b49c1f22c002391c11 HTTP/1.1

###

POST http://localhost:9000/api/restaurant HTTP/1.1
Content-Type: application/json

{
    "nombre":"Sayonara",
    "tipo_comida":"Rápida",
    "calificacion":5,
    "direccion":"Av. 30 de Agosto # 41 - 84 Av. Circunvalar Calle 7 # 14 – 43 Pereira,Risaralda",
    "coordenadas":"R848+X4 Pereira, Risaralda",
    "telefono":3232234363,
    "menu":"{mariscos:30000, burguer:15000}",
    "comentarios":"",
    "plato_destacable":"Hamburguesa",
    "prom_valor": 35000
}

###
GET http://localhost:9000/api/restaurant HTTP/1.1

###
GET http://localhost:9000/api/evaluat HTTP/1.1

###


POST http://localhost:9000/api/evaluat HTTP/1.1
Content-Type: application/json

{

  "id_restaurante":"64acb210ad05a2c6f85f0197",
  "cant_estrellas":3,
  "comentario":"Estuvo super la atención",
  "id_usuario":"Tatiana Granada"
}
